import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision?: string }>;
  __WB_DISABLE_DEV_LOGS: boolean;
};

// Disable dev logs for workbox
self.__WB_DISABLE_DEV_LOGS = true;

// Precache all assets generated by Vite
clientsClaim();
precacheAndRoute(self.__WB_MANIFEST);

// Cache-first for JS, CSS, and images
registerRoute(
  ({ request }) => ['script', 'style', 'image'].includes(request.destination),
  new CacheFirst({
    cacheName: 'static-resources',
    plugins: []
  })
);

// Network-first for navigation (App Shell)
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'html-shell',
    plugins: []
  })
);

// Network-first (with timeout) for API/data endpoints
registerRoute(
  ({ url }) => url.pathname.startsWith('/data/'),
  new NetworkFirst({
    cacheName: 'api-data',
    networkTimeoutSeconds: 3
  })
);